routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TaskRequestController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false
]);

Route::group(['middleware'=>'auth'], function(){

    Route::get('/', function () {
        return view('index');
    })->name('home');

    Route::resource('task', TaskController::class);
    Route::get('task/{id}/comment', [CommentController::class, 'commentModal'])->name('comment.show');
    Route::post('task/{id}/comment', [CommentController::class, 'store'])->name('comment.store');
    Route::get('task/{id}/comment/{comment}', [CommentController::class, 'destroy'])->name('comment.destroy');

    Route::get('taskrequest/{taskrequest}/take', [TaskRequestController::class, 'take'])->name('taskrequest.take');
    Route::resource('taskrequest', TaskRequestController::class);

    Route::get('calendar', function () {
        return view('calendar');
    })->name('calendar');

    Route::get('password', [UserController::class, 'editPassword'])->name('editpass');
    Route::post('password', [UserController::class, 'updatePassword'])->name('updatepass');
    Route::resource('user', UserController::class)->except(['show', 'edit', 'update']);

});

resources/views/partials/comments.blade.php
@if (count($comments) > 0)
    <ul class="list-group">
        @foreach ($comments as $item)
            <li class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <div class="mb-1 fw-bold">{{!empty($item->user_id) ? $item->user->name : 'unknown'}}</div>
                    <small class="text-muted">{{$item->timer}}</small>
                </div>
                <p class="mb-1">{{$item->content}}</p>
                @if (Auth::user()->id == $item->user_id)
                    <small>
                        <a href="{{route('comment.destroy', ['id'=>$task->id, 'comment'=>$item->id])}}" class="text-danger">
                            <span class="material-icons-outlined">delete</span>
                        </a>
                    </small>
                @endif
            </li>
        @endforeach
    </ul>
    @else
    <div class="card">
        <div class="card-body">
            <h3 class="text-muted text-center">No available comments</h3>
        </div>
    </div>
@endif
<div class="card mt-3">
    <div class="card-body">
        <form method="POST" action="{{route('comment.store', ['id'=>$task->id])}}">
            @csrf
            <textarea class="form-control mb-3" name="content" placeholder="add comment">{{old('content')}}</textarea>
            <button class="btn btn-outline-success btn-sm" type="submit">Send Comment</button>
        </form>
    </div>
</div>

resources/views/partials/request.blade.php
@if ($item->status == 'waiting' && Auth::user()->id == $item->reporter_id)
    <a href="{{route('taskrequest.edit', ['taskrequest'=>$item->id])}}" class="btn btn-outline-primary btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit">
        <span class="material-icons-outlined">create</span>
    </a>
    <a href="{{route('taskrequest.destroy', ['taskrequest'=>$item->id])}}" class="btn btn-outline-danger btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete" onclick="event.preventDefault();
        document.getElementById('delete{{$item->id}}').submit();">
        <span class="material-icons-outlined">delete</span>
    </a>
    <form method="POST" class="d-none" id="delete{{$item->id}}" action="{{route('taskrequest.destroy', ['taskrequest'=>$item->id])}}">
        @csrf
        @method('delete')
    </form>
    {{-- <a href="{{route('taskrequest.take', ['taskrequest'=>$item->id])}}" class="btn btn-outline-danger btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Take">
        <span class="material-icons-outlined">pan_tool</span>
    </a> --}}
@endif
<a href="{{route('taskrequest.show', ['taskrequest'=>$item->id])}}" class="btn btn-outline-secondary btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="View Detail">
    <span class="material-icons-outlined">visibility</span>
</a>

resources/views/partials/task.blade.php
@if ($item->type == 'task')
    @if (Auth::user()->id == $item->assignee_id)
        <a href="{{route('task.edit', ['task'=>$item->id])}}" class="btn btn-outline-primary btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit">
            <span class="material-icons-outlined">create</span>
        </a>
    @endif
    <button class="btn btn-outline-success btn-sm" data-bs-toggle="modal" data-bs-target="#showComment" data-bs-url="{{route('comment.show', ['id'=>$item->id])}}">
        <span class="material-icons-outlined">chat_bubble_outline</span>
    </button>
@endif
@if ($item->type != 'weekend')
    <a href="{{route('task.show', ['task'=>$item->id])}}" class="btn btn-outline-{{$item->type == 'task' ? 'secondary' : 'light'}} btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="View Detail">
        <span class="material-icons-outlined">visibility</span>
    </a>
@else
    <button type="button" disabled class="btn btn-outline-light btn-sm">
        <span class="material-icons-outlined">visibility</span>
    </a>
@endif