routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TaskRequestController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false
]);

Route::group(['middleware'=>'auth'], function(){

    Route::get('/', function () {
        return view('index');
    })->name('home');

    Route::resource('task', TaskController::class);
    Route::get('task/{id}/comment', [CommentController::class, 'commentModal'])->name('comment.show');
    Route::post('task/{id}/comment', [CommentController::class, 'store'])->name('comment.store');
    Route::get('task/{id}/comment/{comment}', [CommentController::class, 'destroy'])->name('comment.destroy');

    Route::get('taskrequest/{taskrequest}/take', [TaskRequestController::class, 'take'])->name('taskrequest.take');
    Route::resource('taskrequest', TaskRequestController::class);

    Route::get('calendar', function () {
        return view('calendar');
    })->name('calendar');

    Route::get('password', [UserController::class, 'editPassword'])->name('editpass');
    Route::post('password', [UserController::class, 'updatePassword'])->name('updatepass');
    Route::resource('user', UserController::class)->except(['show', 'edit', 'update']);

});

resources/views/request/form.blade.php
@extends('layouts.main')

@section('title'){{'Request Task'}}@endsection

@section('pagestyle')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" />
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">

                <form method="POST" action="{{ isset($task) ? route('taskrequest.update', ['taskrequest'=>$task->id]) : route('taskrequest.store') }}">
                    @csrf
                    @isset($task)
                        @method('PUT')
                    @endisset
                    <div class="row align-items-center mb-3">
                        <label for="title" class="col-sm-2 col-form-label">Title</label>
                        <div class="col-sm-10">
                            <input type="text" id="title" name="title" class="form-control" value="{{ isset($task) ? $task->title : old('title') }}" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="detail" class="col-sm-2 col-form-label">Detail</label>
                        <div class="col-sm-10">
                            <textarea id="detail" name="detail" class="form-control" required>{{ isset($task) ? $task->detail : old('detail') }}</textarea>
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="assignee" class="col-sm-2 col-form-label">Assigned To</label>
                        <div class="col-sm-10">
                            <select class="form-control select2" name="assignee" id="assignee" data-placeholder="choose assignee" required>
                                <option></option>
                                @foreach ($users as $user)
                                    <option value="{{$user->id}}" {{(isset($task) && $task->assignee_id == $user->id) || old('assignee') == $user->id ? 'selected=selected' : ''}}>{{$user->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="priority" class="col-sm-2 col-form-label">Priority</label>
                        <div class="col-sm-10">
                            <select class="form-control select2" name="priority" id="priority">
                                <option value="low" {{(isset($task) && $task->priority == 'low') || old('priority') == 'low' ? 'selected=selected' : ''}}>Low</option>
                                <option value="mid" {{(isset($task) && $task->priority == 'mid') || old('priority') == 'mid' ? 'selected=selected' : ''}}>Mid</option>
                                <option value="high" {{(isset($task) && $task->priority == 'high') || old('priority') == 'high' ? 'selected=selected' : ''}}>High</option>
                            </select>
                        </div>
                    </div>
                    <hr />
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                    <a href="{{route('taskrequest.index')}}" class="btn btn-outline-secondary">Cancel</a>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous"></script>
<script>
$(document).ready(function() {
    $('.select2').select2();
});
</script>
@endsection

resources/views/request/index.blade.php
@extends('layouts.main')

@section('title'){{'Task Requests'}}@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">

                <div class="table-responsive table-centered">
                    {{$dataTable->table()}}
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
{{$dataTable->scripts()}}
<script type="text/javascript">
$(document).ready(function () {
    $("#{{$dataTable->getTableAttribute('id')}}").on('draw.dt', function () {
        $('[data-bs-toggle="tooltip"]').tooltip();
    });
})
</script>
@endsection

resources/views/request/show.blade.php
@extends('layouts.main')

@section('title'){{'Task Request'}}@endsection

@section('pagestyle')

@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">

                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Title</div>
                    <div class="col-sm-10">{{ $task->title }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-2 fw-bold">Detail</div>
                    <div class="col-sm-10">{{ $task->detail }}</div>
                </div>
                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Reporter</div>
                    <div class="col-sm-10">{{ !empty($task->reporter_id) ? $task->reporter->name : '' }}</div>
                </div>
                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Assignee</div>
                    <div class="col-sm-10">{{ !empty($task->assignee_id) ? $task->assignee->name : '' }}</div>
                </div>
                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Priority</div>
                    <div class="col-sm-10">{{ Str::title($task->priority) }}</div>
                </div>

            </div>
            <div class="card-footer">
                @if ($task->status == 'waiting' && Auth::user()->id == $task->assignee_id)
                    <a href="{{route('taskrequest.take', ['taskrequest'=>$task->id])}}" class="btn btn-outline-success btn-sm">
                        Take this request
                    </a>
                @endif
                <a href="{{route('taskrequest.index')}}" class="btn btn-outline-secondary btn-sm">
                    Back to list
                </a>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>
<script>
$(document).ready(function() {
    $('.select2').select2();
    $('.datepicker').datepicker({
        clearBtn: true,
        format: "yyyy-mm-dd",
        autoclose: true,
        todayHighlight: true
    });
});
</script>
@endsection