routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TaskRequestController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false
]);

Route::group(['middleware'=>'auth'], function(){

    Route::get('/', function () {
        return view('index');
    })->name('home');

    Route::resource('task', TaskController::class);
    Route::get('task/{id}/comment', [CommentController::class, 'commentModal'])->name('comment.show');
    Route::post('task/{id}/comment', [CommentController::class, 'store'])->name('comment.store');
    Route::get('task/{id}/comment/{comment}', [CommentController::class, 'destroy'])->name('comment.destroy');

    Route::get('taskrequest/{taskrequest}/take', [TaskRequestController::class, 'take'])->name('taskrequest.take');
    Route::resource('taskrequest', TaskRequestController::class);

    Route::get('calendar', function () {
        return view('calendar');
    })->name('calendar');

    Route::get('password', [UserController::class, 'editPassword'])->name('editpass');
    Route::post('password', [UserController::class, 'updatePassword'])->name('updatepass');
    Route::resource('user', UserController::class)->except(['show', 'edit', 'update']);

});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    public function reporter(){
        return $this->belongsTo(User::class, 'reporter_id', 'id');
    }

    public function assignee(){
        return $this->belongsTo(User::class, 'assignee_id', 'id');
    }

    public function asked(){
        if(!empty($this->request_id)){
            return $this->hasOne(TaskRequest::class, 'id', 'request_id');
        }
        return null;
    }

    public function comments(){
        return $this->hasMany(Comment::class, 'task_id', 'id')->orderBy('created_at', 'DESC');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\DataTables\TaskDataTable;
use App\Models\Task;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(TaskDataTable $dataTable, Request $request)
    {
        return $dataTable->with('request',$request)->render('task.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        return view('task.form', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'reported_at' => 'required|date',
            'type' => 'required'
        ]);

        $task = new Task();
        $task->reported_at = $request->reported_at;
        $task->title = $request->title;
        $task->detail = $request->detail;
        $task->hours = $request->hours;
        $task->reporter_id = $request->reporter;
        $task->assignee_id = $request->assignee;
        $task->priority = $request->priority;
        $task->type = $request->type;

        if ($task->save()) {
            return redirect()->route('task.index')->with('message', 'you have successfully added new task');
        }else{
            return redirect()->route('task.index')->with('message', 'sorry, you have unsuccessfully added new task');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::findOrFail($id);
        return view('task.show', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::all();
        $task = Task::findOrFail($id);
        return view('task.form', compact('users', 'task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $task = Task::find($id);
        $task->reported_at = $request->reported_at;
        $task->title = $request->title;
        $task->detail = $request->detail;
        $task->hours = $request->hours;
        $task->reporter_id = $request->reporter;
        $task->assignee_id = $request->assignee;
        $task->priority = $request->priority;
        $task->type = $request->type;

        if ($task->save()) {
            return redirect()->route('task.index')->with('message', 'you have successfully updated the task');
        }else{
            return redirect()->route('task.index')->with('message', 'sorry, you have unsuccessfully updated the task');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);
        if ($task->delete()) {
            return redirect()->route('task.index')->with('message', 'you have successfully deleted the task');
        }else{
            return redirect()->route('task.index')->with('message', 'sorry, you have unsuccessfully deleted the task');
        }
    }
}

resources/views/task/form.blade.php
@extends('layouts.main')

@section('title'){{'Daily Tasks'}}@endsection

@section('pagestyle')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">

                <form method="POST" action="{{ isset($task) ? route('task.update', ['task'=>$task->id]) : route('task.store') }}">
                    @csrf
                    @isset($task)
                        @method('PUT')
                    @endisset
                    <div class="row align-items-center mb-3">
                        <label for="title" class="col-sm-2 col-form-label">Title</label>
                        <div class="col-sm-10">
                            <input type="text" id="title" name="title" class="form-control" value="{{ isset($task) ? $task->title : old('title') }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="detail" class="col-sm-2 col-form-label">Detail</label>
                        <div class="col-sm-10">
                            <textarea id="detail" name="detail" class="form-control">{{ isset($task) ? $task->detail : old('detail') }}</textarea>
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="reporter" class="col-sm-2 col-form-label">Reporter</label>
                        <div class="col-sm-10">
                            <select class="form-control select2" name="reporter" id="reporter" data-placeholder="Choose reporter">
                                <option></option>
                                @foreach ($users as $user)
                                    <option value="{{$user->id}}" {{(isset($task) && $task->reporter_id == $user->id) || old('reporter') == $user->id ? 'selected=selected' : ''}}>{{$user->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="assignee" class="col-sm-2 col-form-label">Assignee</label>
                        <div class="col-sm-10">
                            <select class="form-control select2" name="assignee" id="assignee" data-placeholder="Choose assignee">
                                <option></option>
                                @foreach ($users as $user)
                                    <option value="{{$user->id}}" {{(isset($task) && $task->assignee_id == $user->id) || old('assignee') == $user->id ? 'selected=selected' : ''}}>{{$user->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="hours" class="col-sm-2 col-form-label">Hours</label>
                        <div class="col-sm-10">
                            <input type="number" id="hours" name="hours" class="form-control" value="{{ isset($task) ? $task->hours : old('hours') }}">
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="reported_at" class="col-sm-2 col-form-label">Reported Date</label>
                        <div class="col-sm-10">
                            <input type="text" id="reported_at" name="reported_at" class="form-control datepicker" value="{{ isset($task) ? $task->reported_at : old('reported_at') }}">
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="priority" class="col-sm-2 col-form-label">Priority</label>
                        <div class="col-sm-10">
                            <select class="form-control select2" name="priority" id="priority">
                                <option value="low" {{(isset($task) && $task->priority == 'low') || old('priority') == 'low' ? 'selected=selected' : ''}}>Low</option>
                                <option value="mid" {{(isset($task) && $task->priority == 'mid') || old('priority') == 'mid' ? 'selected=selected' : ''}}>Mid</option>
                                <option value="high" {{(isset($task) && $task->priority == 'high') || old('priority') == 'high' ? 'selected=selected' : ''}}>High</option>
                            </select>
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="type" class="col-sm-2 col-form-label">Type</label>
                        <div class="col-sm-10">
                            <select class="form-control select2" name="type" id="type">
                                <option value="task" {{(isset($task) && $task->type == 'task') || old('type') == 'task' ? 'selected=selected' : ''}}>Task</option>
                                <option value="weekend" {{(isset($task) && $task->type == 'weekend') || old('type') == 'weekend' ? 'selected=selected' : ''}}>Weekend</option>
                                <option value="offday" {{(isset($task) && $task->type == 'offday') || old('type') == 'offday' ? 'selected=selected' : ''}}>Off Day</option>
                            </select>
                        </div>
                    </div>
                    <hr />
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                    <a href="{{route('task.index')}}" class="btn btn-outline-secondary">Cancel</a>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>
<script>
$(document).ready(function() {
    $('.select2').select2();
    $('.datepicker').datepicker({
        clearBtn: true,
        format: "yyyy-mm-dd",
        autoclose: true,
        todayHighlight: true
    });
});
</script>
@endsection

resources/views/task/index.blade.php
@extends('layouts.main')

@section('title'){{'Daily Tasks'}}@endsection

@section('pagestyle')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <div class="input-group mb-3">
                    <input type="text" class="form-control datepicker" name="month" id="monthInput" placeholder="Filter by Month" readonly>
                    <button class="btn btn-outline-secondary" type="button" id="filterMonth">Get</button>
                </div>
                <div class="table-responsive table-centered">
                    {{$dataTable->table()}}
                </div>

            </div>
            <div class="card-footer">
                <span class="weekend">Weekend</span>
                <span class="offday">National Off Day</span>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="showComment" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Comments</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>
{{$dataTable->scripts()}}
<script type="text/javascript">
$(document).ready(function () {
    $("#{{$dataTable->getTableAttribute('id')}}").on('draw.dt', function () {
        $('[data-bs-toggle="tooltip"]').tooltip();
    });
    $('#showComment').on('show.bs.modal', function(e){
        var button = e.relatedTarget;
        var url = button.getAttribute('data-bs-url');
        $.get(url).done(function(data){
            var body = $('#showComment').find('.modal-body');
            body.html('');
            body.html(data.html);
        })
    });
    $(".datepicker").datepicker( {
        format: "mm-yyyy",
        startView: "months",
        minViewMode: "months"
    });
    $('#filterMonth').click(function () {
        var param = $('#monthInput').val();
        LaravelDataTables["task-table"].column(0)
        .search( param ? param : '', false, false );
        LaravelDataTables["task-table"].table().draw();
    });
})
</script>
@endsection

resources/views/task/print.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Print Table</title>
        <meta charset="UTF-8">
        <meta name=description content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;600;700&family=Material+Icons+Outlined&display=swap" rel="stylesheet">
        <style type="text/css">
            body {
                -webkit-print-color-adjust:exact;
                margin: 20px;
                font-size: .875rem;
                font-family: 'Nunito', sans-serif;
                font-weight: 300;
            }
            table{
                width: 100%;
                border-collapse: collapse;
                border: 1px solid #333;
            }

            table tr th, table tr td{
                padding: 5px;
                border: 1px solid #333;
            }
            tr.weekend {
                background: #00695c !important;
                color: #fff !important;
                -webkit-print-color-adjust: exact;
            }
            tr.offday {
                background: #1565c0 !important;
                color: #fff !important;
                -webkit-print-color-adjust: exact;
            }
            span.weekend, span.offday{
                padding-left: 23px;
                position: relative;
                display: inline-flex;
                align-items: center;
            }

            span.weekend{
                margin-right: 10px;
            }

            span.weekend:before, span.offday:before{
                content: "";
                width: 20px;
                height: 20px;
                border: 1px solid #fff;
                border-radius: 50%;
                left: 0;
                position: absolute;
            }

            span.weekend:before{
                background-color: #00695c;
            }
            span.offday:before{
                background-color: #1565c0;
            }
            .text-center{
                text-align: center;
            }
            .text-right{
                text-align: right;
            }
        </style>
        <style type="text/css" media="print">
            @media print {
                body {
                    background: transparent;
                    -webkit-print-color-adjust:exact;
                }
                tr.weekend {
                    background: #00695c !important;
                    color: #fff !important;
                    -webkit-print-color-adjust: exact;
                }
                tr.offday {
                    background: #1565c0 !important;
                    color: #fff !important;
                    -webkit-print-color-adjust: exact;
                }
            }
        </style>
    </head>
    <body>
        @php
            if(!empty(request()->columns[0]['search']['value'])){
                $dateArr = explode('-', request()->columns[0]['search']['value']);
                $createDate = \Carbon\Carbon::createFromDate($dateArr[1], $dateArr[0], 1)->format('F Y');
            }
        @endphp
        @if (!empty(request()->columns[0]['search']['value']))
            <h2 class="text-center">{{$createDate}}</h2>
        @endif
        <table class="table table-bordered table-condensed table-striped">
            @foreach($data as $row)
                @if ($loop->first)
                    <tr>
                        @foreach($row as $key => $value)
                            @if ($key != 'Type')
                            <th>{!! $key !!}</th>
                            @endif
                        @endforeach
                    </tr>
                @endif
                <tr class="{{$row['Type']}}">
                    @if ($row['Type'] == 'weekend')
                        <td colspan="6">{!! $row['Date'] !!}</td>
                    @elseif ($row['Type'] == 'offday')
                        <td>{!! $row['Date'] !!}</td>
                        <td colspan="5" class="text-center">--- {!! $row['Task'] !!} ---</td>
                    @else
                        @foreach($row as $key => $value)
                            @if ($key != 'Type')
                            <td class="{{is_numeric($value) ? 'text-right': ''}}">{!! $value !!}</td>
                            @endif
                        @endforeach
                    @endif
                </tr>
            @endforeach
                <tr>
                    <td colspan="6">
                        <span class="weekend">Weekend</span>
                        <span class="offday">National Off Day</span>
                    </td>
                </tr>
        </table>
    </body>
</html>

resources/views/task/show.blade.php
@extends('layouts.main')

@section('title'){{'Daily Tasks'}}@endsection

@section('pagestyle')

@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">

                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Title</div>
                    <div class="col-sm-10">{{ $task->title }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-2 fw-bold">Detail</div>
                    <div class="col-sm-10">{{ $task->detail }}</div>
                </div>
                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Reporter</div>
                    <div class="col-sm-10">{{ !empty($task->reporter_id) ? $task->reporter->name : '' }}</div>
                </div>
                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Assignee</div>
                    <div class="col-sm-10">{{ !empty($task->assignee_id) ? $task->assignee->name : '' }}</div>
                </div>
                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Hours</div>
                    <div class="col-sm-10">{{ $task->hours }}</div>
                </div>
                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Date</div>
                    <div class="col-sm-10">{{ $task->reported_at }}</div>
                </div>
                <div class="row align-items-center mb-3">
                    <div class="col-sm-2 fw-bold">Type</div>
                    <div class="col-sm-10">{{ Str::title($task->type) }}</div>
                </div>

            </div>
            <div class="card-footer">
                @if ($task->type == 'task')
                    <button class="btn btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#commentBox" aria-expanded="false" aria-controls="commentBox">
                        Show Comments
                    </button>
                @endif
                <a href="{{route('task.index')}}" class="btn btn-outline-secondary">Back to list</a>
            </div>
        </div>
        @if ($task->type == 'task')
            <div class="collapse mt-3" id="commentBox">
                @if (count($task->comments) > 0)
                    <ul class="list-group">
                        @foreach ($task->comments as $item)
                            <li class="list-group-item">
                                <div class="d-flex w-100 justify-content-between">
                                    <div class="mb-1 fw-bold">{{!empty($item->user_id) ? $item->user->name : 'unknown'}}</div>
                                    <small class="text-muted">{{$item->timer}}</small>
                                </div>
                                <p class="mb-1">{{$item->content}}</p>
                                <small>
                                    <a href="{{route('comment.destroy', ['id'=>$task->id, 'comment'=>$item->id])}}" class="text-danger">
                                        <span class="material-icons-outlined">delete</span>
                                    </a>
                                </small>
                            </li>
                        @endforeach
                    </ul>
                @else
                    <div class="card">
                        <div class="card-body">
                            <h3 class="text-muted text-center">No available comments</h3>
                        </div>
                    </div>
                @endif
                <div class="card mt-3">
                    <div class="card-body">
                        <form method="POST" action="{{route('comment.store', ['id'=>$task->id])}}">
                            @csrf
                            <textarea class="form-control mb-3" name="content" placeholder="add comment">{{old('content')}}</textarea>
                            <button class="btn btn-outline-success btn-sm" type="submit">Send Comment</button>
                        </form>
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection

@section('script')

@endsection