routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TaskRequestController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false
]);

Route::group(['middleware'=>'auth'], function(){

    Route::get('/', function () {
        return view('index');
    })->name('home');

    Route::resource('task', TaskController::class);
    Route::get('task/{id}/comment', [CommentController::class, 'commentModal'])->name('comment.show');
    Route::post('task/{id}/comment', [CommentController::class, 'store'])->name('comment.store');
    Route::get('task/{id}/comment/{comment}', [CommentController::class, 'destroy'])->name('comment.destroy');

    Route::get('taskrequest/{taskrequest}/take', [TaskRequestController::class, 'take'])->name('taskrequest.take');
    Route::resource('taskrequest', TaskRequestController::class);

    Route::get('calendar', function () {
        return view('calendar');
    })->name('calendar');

    Route::get('password', [UserController::class, 'editPassword'])->name('editpass');
    Route::post('password', [UserController::class, 'updatePassword'])->name('updatepass');
    Route::resource('user', UserController::class)->except(['show', 'edit', 'update']);

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\UserDataTable;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Auth\SendsPasswordResetEmails;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
use App\Rules\CurrentPassword;

class UserController extends Controller
{
    use SendsPasswordResetEmails;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(UserDataTable $dataTable)
    {
        return $dataTable->render('user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => 'unique:users'
        ]);
        $rand = Str::random(12);
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($rand),
            'role' => $request->role,
        ]);

        if($user){
            if (isset($request->send_email)) {
                $this->broker()->sendResetLink(
                    $request->only('email')
                );
            }
            return redirect()->route('user.index')->with('message', 'you have successfully added new user');
        }else{
            return redirect()->route('user.index')->with('message', 'sorry, you have unsuccessfully added new user');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if ($user->delete()) {
            return redirect()->route('user.index')->with('message', 'you have successfully deleted the user');
        }else{
            return redirect()->route('user.index')->with('message', 'sorry, you have unsuccessfully deleted the user');
        }
    }

    public function editPassword()
    {
        return view('password');
    }

    public function updatePassword(Request $request)
    {
        $this->validate($request,[
            'old_password'=>['required',new CurrentPassword()],
            'password'=>'required|string|min:8',
        ]);

        $password = $request->password;
        $user = Auth::user();
        $user->password = Hash::make($password);
        if ($user->save()) {
            return redirect()->route('home')->with('message', 'you have successfully updated your password');
        }else{
            return redirect()->route('home')->with('message', 'sorry, you have unsuccessfully updated your password');
        }
    }
}

resources/views/user/form.blade.php
@extends('layouts.main')

@section('title'){{'Users'}}@endsection

@section('pagestyle')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" />
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">

                <form method="POST" action="{{ isset($user) ? route('user.update', ['user'=>$user->id]) : route('user.store') }}">
                    @csrf
                    @isset($task)
                        @method('PUT')
                    @endisset
                    <div class="row align-items-center mb-3">
                        <label for="name" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" id="name" name="name" class="form-control" value="{{ isset($user) ? $user->name : old('name') }}" required>
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="email" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" id="email" name="email" class="form-control" value="{{ isset($user) ? $user->email : old('email') }}" required>
                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <label for="role" class="col-sm-2 col-form-label">Role</label>
                        <div class="col-sm-10">
                            <select class="form-control select2" name="role" id="role">
                                <option value="assignee" {{(isset($user) && $user->role == 'assignee') || old('role') == 'assignee' ? 'selected=selected' : ''}}>Assignee</option>
                                <option value="reporter" {{(isset($user) && $user->role == 'reporter') || old('role') == 'reporter' ? 'selected=selected' : ''}}>Reporter</option>
                                <option value="superadmin" {{(isset($user) && $user->role == 'superadmin') || old('role') == 'superadmin' ? 'selected=selected' : ''}}>Superadmin</option>
                            </select>
                        </div>
                    </div>
                    <div class="row align-items-center mb-3">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-10">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" name="send_email">
                                <label class="form-check-label" for="flexCheckDefault">
                                    Send email?
                                </label>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                    <a href="{{route('user.index')}}" class="btn btn-outline-secondary">Cancel</a>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous"></script>
<script>
$(document).ready(function() {
    $('.select2').select2();
});
</script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.main')

@section('title'){{'Users'}}@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">

                <div class="table-responsive table-centered">
                    {{$dataTable->table()}}
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
{{$dataTable->scripts()}}
<script type="text/javascript">
$(document).ready(function () {
    $("#{{$dataTable->getTableAttribute('id')}}").on('draw.dt', function () {
        $('[data-bs-toggle="tooltip"]').tooltip();
    });
})
</script>
@endsection